site_name: Majorli's Blogs
site_description: Projects and notes about algorithms, data structures, mathematics, machine learning and so on
site_author: MajorLi
site_url: https://majorli.github.io/

repo_name: majorli/majorli.github.io
repo_url: https://github.com/majorli/majorli.github.io

nav:
        - Home: 
                - index.md
                - 更博日志:
                        - journal_may_2020.md
                        - journal_apr_2020.md
        - Projects:
                - projects/algo_guide.md
        - Algorithms:
                - notes/algos/overview.md
                - notes/algos/prime_algos.md
                - notes/algos/kth.md
                - notes/algos/perm_comb.md

theme:
        name: material
        site_dir: '../blogs_site'
        palette:
                primary: teal
                accent: teal
        features:
                - tabs
        favicon: images/favicon.png
        logo: images/jeans.png
        language: zh

markdown_extensions:
        - admonition
        - attr_list
        - toc:
                permalink: true
        - pymdownx.highlight:
                linenums: true
        - pymdownx.superfences
        - pymdownx.details
        - pymdownx.inlinehilite
        - pymdownx.caret
        - pymdownx.arithmatex
        - pymdownx.magiclink
        - pymdownx.mark
        - pymdownx.tasklist
        - pymdownx.tilde
        - pymdownx.critic
        - pymdownx.tabbed

plugins:
        - search

extra_javascript:
        - https://cdn.bootcss.com/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
#       - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
